### ISSUE TITLE
Help: Why pylint gives me an error of `no-member`?

### ISSUE THREAD

**Issue by ZJUGuoShuai** [kennethreitz/crayons#23]
Why pylint gives me an error `Module 'crayons' has no 'yellow' member` when I write
```python
import crayons
...
...
print(crayons.yellow("Bot > " + response(query), bold=True))
```

**Comment by timofurrer** [comment]
`crayons` generates the color functions like `crayons.yellow`, `crayons.red`, ... dynamically.
There is no way for `pylint` to know that those functions actually exists.
